### ISSUE TITLE
how can i change keyboard shortcut for this package?

### ISSUE THREAD

**Issue by hemedani** [TheDutchCoder/ColorConvert#20]
I want change the keyboard shortcut because it's conflict with another package how can i do that?
Tanx

**Comment by TheDutchCoder** [comment]
You can go to Preferences > Key bindings (user) and add:
```js
  {
    "keys": ["ctrl+shift+c"], "command": "colorconvert"
  }
```

There you can override the default command to whatever you'd like.
More info here: http://docs.sublimetext.info/en/latest/customization/key_bindings.html
