### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [TheDutchCoder/ColorConvert#21]
Hi.Good work. Do u think it's possible to write same for Synwrite?
https://sourceforge.net/p/synwrite/wiki/python%20API/
if u refactor code, so convert is a separate Def, i can make it

**Comment by Alexey-T** [comment]
I meaned:

    def get_new_textline(textline, caret_offset_in_line)

**Comment by TheDutchCoder** [comment]
Feel free to fork the repo or submit a PR ;-)
