### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by danielzfranklin** [TheDutchCoder/ColorConvert#22]
I would love to use this in a project I am working on. What is the license?

**Comment by nathanboktae** [comment]
It doesn't matter what it is as it's not part of your source or IP.

**Comment by danielzfranklin** [comment]
Yes it does. I can't copy your code into my project unless you have a license allowing me to do so. 

By default, it is copyright and I can't incorporate it into my own project or use it without your permission.

**Comment by nathanboktae** [comment]
ah you want to incorporate it into another sublime package. Got it. Yes you're right.

**Comment by danielzfranklin** [comment]
I want to modify it and incorporate it into a website (that has no aim of getting a profit). Would this be alright?

**Comment by nathanboktae** [comment]
I'm not the owner just a random dude on the internet :)

**Comment by danielzfranklin** [comment]
*Hits head*

**Comment by TheDutchCoder** [comment]
Hey man feel free to use/copy/modifiy my code, but please just credit me somewhere.
I didn't include a license, sorry about that.

You could consider this a "don't be a douche license" :)

**Comment by danielzfranklin** [comment]
Sorry to bother you again, just want to make sure I'm not in legal danger in the future.

For legal reasons, can we say that you are giving me permission to use the project under the terms of the [Apache 2.0](http://choosealicense.com/licenses/apache-2.0/) license?

## Github's explanation:

Required
* License and copyright notice
* State Changes

Permitted
* Commercial Use
* Distribution
* Modification
* Patent Grant
* Private Use
* Sublicensing

Forbidden
* Hold Liable
* Use Trademark

**Comment by TheDutchCoder** [comment]
Sure, go ahead!
